CREATE TABLE 'test'.'customer' (
	'id' MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
	'firstName' VARCHAR(255) NULL,
	'lastName' VARCHAR(255) NULL,
	'birthdate' VARCHAR(255) NULL,
PRIMARY KEY ('id')
) AUTO_INCREMENT=1;